django_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
path('',include("locallibrary.urls")),
    path("accounts/",include('django.contrib.auth.urls'))
]

"""
 path("accounts/",include('django.contrib.auth.urls'))
 the auth app urls is this it is like you add those :
accounts/ login/ [name='login']
accounts/ logout/ [name='logout']
accounts/ password_change/ [name='password_change']
accounts/ password_change/done/ [name='password_change_done']
accounts/ password_reset/ [name='password_reset']
accounts/ password_reset/done/ [name='password_reset_done']
accounts/ reset/<uidb64>/<token>/ [name='password_reset_confirm']
accounts/ reset/done/ [name='password_reset_complete']
"""

locallibrary/urls.py
from django.urls import path,include,re_path
from .views import index,BooksList,book_detail,AuthorsList,\
    author_detail,LoanedBooksByUserListView,AvailableBooksView,BorrowedBooksView,\
    renew_book_librarian,AuthorCreate,AuthorDelete,AuthorUpdate,CreateBookView,UpdateBookView,DeleteBookView
urlpatterns = [
    path('', index, name='index'),
    path('books/',BooksList.as_view(),name='books'),
    re_path(r'^books/(?P<pk>\d+)/$',book_detail.as_view(),name='details'),
    path('authors/',AuthorsList.as_view() ,name="authors" ),
    re_path(r'^authors/(?P<pk>\d+)/$',author_detail.as_view(),name="author_detail"),
path('mybooks/', LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('avabooks/',AvailableBooksView.as_view(),name="available"),
    path('borrowed/',BorrowedBooksView.as_view(),name='borrow'),
    path('book/<uuid:pk>/renew/', renew_book_librarian, name='renew-book-librarian'),
    path('book/<int:pk>/delete',DeleteBookView.as_view(),name="del"),

#***
path('author/create',AuthorCreate.as_view(),name='author-create'),
    path('author/<int:pk>/update/', AuthorUpdate.as_view(), name='author-update'),
    path('author/<int:pk>/delete/',AuthorDelete.as_view(), name='author-delete'),
    path('book/create',CreateBookView.as_view(),name="book-create"),
    path('book/<int:pk>/update',UpdateBookView.as_view(),name="book-update")

]



#"hhhh لاحظي عندك في اليورل الثالت والاخير استعملنا  pk
#بس بالثالثة لازم تسمي الفاريبل ببرايمي كي لانهها generic detail view
#لكن الي بعدها فنكشن بنقدر نسميه الي بدنا اياه حسب الفنكشن شو حتسمي الباراميتر تاعها#

locallibrary/models.py
from django.db import models
from django.contrib import admin
from datetime import date,datetime
from django.contrib.auth.models import User
# Create your models here.
now=datetime.now()

class Genre(models.Model):
    name=models.CharField(max_length=200,help_text="Enter a book genre e.g fiction Science ")
    def __str__(self):
        return self.name
from django.urls import reverse # Used to generate URLs by reversing the URL patterns
class Language(models.Model):
    name=models.CharField(help_text="enter a language e.g French,English,Arabic..",max_length=100)
    def __str__(self):
        return self.name
class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    title = models.CharField(max_length=200)
    pub_date=models.DateTimeField("date",default=datetime.today())

    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author is a string rather than an object because it hasn't been declared yet in the file
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)

    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book')
    isbn = models.CharField('ISBN', max_length=13, unique=True,
                             help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')

    # ManyToManyField used because genre can contain many books. Books can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')
    language=models.ForeignKey(Language,on_delete=models.RESTRICT)
    @admin.display(description="Genre")
    def display_genre(self):
        return ",".join(gen.name for gen in self.genre.all()[:3])


    def __str__(self):
        """String for representing the Model object."""
        return self.title

    def get_absolute_url(self):
        """Returns the URL to access a detail record for this book."""
        return reverse('details', args=[str(self.id)])
import uuid # Required for unique book instances

class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey('Book', on_delete=models.CASCADE, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )
    """
('m', 'Maintenance'): This represents the code 'm' and its corresponding label 'Maintenance'. This status indicates that the item is undergoing maintenance and is not available for loan.

('o', 'On loan'): This represents the code 'o' and its corresponding label 'On loan'. This status indicates that the item has been borrowed and is currently on loan.

('a', 'Available'): This represents the code 'a' and its corresponding label 'Available'. This status indicates that the item is available for borrowing.

('r', 'Reserved'): This represents the code 'r' and its corresponding label 'Reserved'. This status indicates that the item has been reserved by a user and is waiting for them to borrow it."""

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',
    )

    @property
    def is_overdue(self):
        """Determines if the book is overdue based on due date and current date."""
        return bool( self.due_back and date.today() > self.due_back)
    """Note: We first verify whether due_back is empty before making a comparison.
     An empty due_back field would cause Django 
     to throw an error instead of showing the page: empty values are not comparable
    . This is not something we would want our users to experience!  
    Notice here the proceeding of expressions and before and is a single expression and after and is a single expression
    self.due_back : 1st expression 
    date.today() > self.due_back: 2th expression"""

    class Meta:
        ordering = ['due_back']
        permissions=(("view_borrowed_books","View what has been borrowed"),)

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.book.title})'
class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    #. The null=True allows the field to have a NULL value in the database,
    # and blank=True means the field can be left empty in forms.
    date_of_death = models.DateField('died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        """Returns the URL to access a particular author instance."""
        return reverse('author_detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.last_name}, {self.first_name}'
"""
from locallibrary.models import Genre,Book,Author,Language
>>> lan=Language.objects.get(name="English")
>>> author=Author.objects.get(first_name="Jeff")
>>> author.last_name
'Kinney'
>>> gnr1=Genre.objects.get(name="Fantasy")
>>> gnr2=Genre.objects.get(name="Classics")
>>> book=Book.objects.create(title="manar test book",author=author,language=lan,isbn="0064471047",summary="please work book")
Traceback (most recent call last):
"""

locallibrary/forms.py
import datetime
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django import forms
from .models import BookInstance
class RenewBookForm(forms.ModelForm):
    def clean_renewal_date(self):
        data=self.cleaned_data["due_back"]
        if data< datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))
        if data>datetime.date.today()+datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))
        return data
    class Meta:
        model=BookInstance
        fields=['due_back']
        labels={"due_back":_("Renewal date")}
        help_text={"due_back":_("Enter a date between now and 4 weeks (default 3).")}

"""
from django import forms
**Validation for just one field
class MyForm(forms.Form):
    username = forms.CharField(max_length=50)

    def clean_username(self):
        username = self.cleaned_data['username']
        if len(username) < 3:
            raise forms.ValidationError("Username must be at least 3 characters long.")
        return username
            ________________________________________________________________________
from django import forms
**Validations for more just one field
class ContactForm(forms.Form):
    name = forms.CharField(max_length=50)
    has_phone = forms.BooleanField(required=False)
    phone_number = forms.CharField(max_length=15, required=False)

    def clean(self):
        cleaned_data = super().clean()
        has_phone = cleaned_data.get("has_phone")
        phone_number = cleaned_data.get("phone_number")

        if has_phone and not phone_number:
            raise forms.ValidationError("Please provide a phone number if you have selected the option.")

"""

locallibrary/templates/author_details.html
{% extends "base_generic.html" %}
{% block content %}
<h1>Author: {{author.first_name}} {{author.last_name}}</h1>
{% for book in author.book_set.all %}
<a href="{{book.get_absolute_url}}"><h2>{{book.title }}</h2></a>
<p>     {{book.summary}}</p>
{% endfor %}
{% endblock %}

locallibrary/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block title %}
      <title>Local Library</title>
    {% endblock %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous" />
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
  </head>
  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-2">
          {% block sidebar %}
            <ul class="sidebar-nav">
              <li><a href="{% url 'index' %}">Home</a></li>
              <li><a href="{% url 'books' %} ">All books</a></li>
              <li><a href="{% url 'authors' %}">All authors</a></li>
                <li><a href="{% url 'my-borrowed' %}">Borrowed</a></li>
                <li><a href="{% url 'available' %}">Available Books </a></li>
                <li><a href="{% url 'borrow' %}">All Borrowed Books </a></li>
                <li><a href="{% url 'book-create' %}">Add  A new Book  </a></li>
            </ul>
          {% endblock %}
        </div>

        <div class="col-sm-10 ">{% block content %}

        {% endblock %}</div>
        <div class="col-sm-10 ">
        {% block pagination %}
    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
<!-- In web development, user authentication typically means whether a user is logged in or not. -->
   {% if user.is_authenticated %}
     <li>User: {{ user.get_username }}</li>
     <li><a href="{% url 'logout' %}?next={{ request.path }}">Logout</a></li>
<!--?next={{ request.path }} is appended to the URL.
This is typically used to redirect the user to their current page after logging out.
request.path dynamically retrieves the current page's URL.            -->
   {% else %}
     <li><a href="{% url 'login' %}?next={{ request.path }}">Login</a></li>
   {% endif %}

  {% endblock %}</div>

        </div>
    </div>
  </body>
</html>

locallibrary/templates/details.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong> <a href="{{book.author.get_absolute_url}}">{{ book.author }}</a></p>
  <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
<p><strong>Date:</strong>{{ book.pub_date|date:"F-- j, Y" }}</p>


  <p><strong>Language:</strong> {{ book.language }}</p>
  <p><strong>Genre:</strong>{{book.genre.all|join:", "}}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
      <hr />
      <p
        class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}display-4 fst-italic{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}
        <!--This function is automatically created because BookInstance.
        status is a choices field. Django automatically creates a method get_FOO_display()
        for every choices field "Foo" in a model, which can be used to get the current value of the field.-->

      </p>
      {% if copy.status != 'a' %}
        <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
      {% endif %}
      <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
      <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
    {% endfor %}
  </div>
{% endblock %}

locallibrary/templates/index.html
{% extends "base_generic.html" %}

{% block title %}<title>Home Page</title> {% endblock %}
{% block content %}
<h1>Local Library Home</h1>
<p>a library made by
<em>Manar Atalla with MDN tutorial Help </em></p>
<h3>The Libray Has The Following records counts:</h3>
<ul>
    <li><p><strong>Books:</strong>{{num_books}}</p></li>
    <li><strong>Copies:</strong> {{ num_instances }}</li>
    <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
    <li><strong>my books:</strong> {{ the }}</li>
    <li><strong>fiction books:</strong> {{ fiction }}</li>
</ul>
<h2>Dynamic content</h2>

<p>The library has the following record counts:</p>
<ul>
  <li><strong>Books:</strong> {{ num_books }}</li>
  <li><strong>Copies:</strong> {{ num_instances }}</li>
  <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
  <li><strong>Authors:</strong> {{ num_authors }}</li>

</ul>

<p>
  You have visited this page {{ num_visits }} time{{ num_visits|pluralize }}.
</p>


{% endblock %}